#include "oled.h"

#define OLED_INIT_CMDS {\
  0x00, /* command stream */                                      \
  0xAF, /* set display off */                                     \
  0xD5, /* set display clock divide ratio/oscillator frequency */ \
  0x80,                                                           \
  0xA8, /* set multiplex ration */                                \
  0x3F,                                                           \
  0xD3, /* set display offset */                                  \
  0x00,                                                           \
  0x40, /* set display start line */                              \
  0x8D, /* set charge pump */                                     \
  0x14, /* VCC generated by internal DC/DC circuit */             \
  0xA0, /* set segment re-map */                                  \
  0xC0, /* set COM output scan direction */                       \
  0xDA, /* set COM pins hardware configuration */                 \
  0x12,                                                           \
  0x81, /* set contrast control */                                \
  0xCF,                                                           \
  0xD9, /* set pre-changed period */                              \
  0xF1,                                                           \
  0xDB, /* set VCOMH deselected level */                          \
  0x40,                                                           \
  0xA4, /* set entire display on */                               \
  0xA6, /* set normal display */                                  \
  0x20, /* set memory address mode */                             \
  0x10, /* page adressing */                                      \
  0xAF, /* set display on */                                      \
}

static uint8_t write_buf[PAGE_NUM][SEGMENT_NUM + 1];

void init_oled(){
  int i2c_master_port = 0;

  i2c_config_t conf = {
    .mode = I2C_MODE_MASTER,
    .sda_io_num = OLED_MASTER_SDA_IO,
    .sda_pullup_en = GPIO_PULLUP_ENABLE,
    .scl_io_num = OLED_MASTER_SCL_IO,
    .scl_pullup_en = GPIO_PULLUP_ENABLE,
    .master.clk_speed = OLED_MASTER_FREQ_HZ,
    .clk_flags = 0,
  };

  i2c_param_config(i2c_master_port, &conf);

  i2c_driver_install(i2c_master_port, conf.mode, 0, 0, 0);

  i2c_master_write_to_device(i2c_master_port, 0x3C, initialize, sizeof(initialize), 1000 / portTICK_PERIOD_MS);

}
